/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;

namespace Rextester
{
    public class Program
    {           
        //rekurencyjnie (wolniej?)
		static int Fib(int n)
		{
			if (n == 0) return 0;
			if (n == 1) return 1;
			return Fib(n-1) + Fib(n-2);
		}
		
		public static void Main(string[] args)
        {
            int[] FibArr = new int[50];
            FibArr[0] = 1;
            FibArr[1] = 2;
			int sum = 2;
            
            //iteracyjnie
            for (int i = 2; i < 50; i++)
            {
                FibArr[i] = FibArr[i-1] + FibArr[i-2];
                if (FibArr[i] > 4000000) break;
                else if (FibArr[i] % 2 == 0) sum += FibArr[i];
            }
           
            Console.WriteLine("Sum of even Fibs below 4'000'000 = {0}", sum);
        }
    }
}